---
title: "Exploring Journalism as a Commodity Through Tracery Live."
description: |
    Using Random Algorithmic Text Generation to Creativly Critique the Journalism Industry
author:
  - name: Natasha Munn 
date: 09-26-2024
output:
  distill::distill_article:
    self_contained: false
---

Kia Ora! I haven’t posted in a while, so I thought I’d return with something different.

For this project, I explored a new language I had never used before, called [***Tracery Live.***](https://gregoryaveryweir.github.io/tracery-live/) Tracery allows you to construct texts using algorithmic generation, enabling you to refresh and shuffle text to create an ever-changing document.

I wanted to use the Tracery format to produce a social commentary on communication. Then, my inspiration stuck when I read a serious article on a local news site. All I wanted was to get up to date on information, but then I was bombarded with Burger King ads in the middle of the article. This led me to want to investigate the commercialization of news sites and the treatment of journalism as a commodity. To accomplish this, I used Tracery to create a stark contrast between the serious topics in breaking news and the intrusive nature of advertising. I made headlines with the intent of causing concern to the reader and connecting them to serious issues in the news, such as politics, law, technology, crime, and sports. My original plan was to make the stories serious as well, but then I decided to lean into a parody of the commercialization of journalism. You can check out the final product by clicking
 [***here.***](https://gregoryaveryweir.github.io/tracery-live/?json=XQAAAAIIKwAAAAAAAAA9iInnY8eHJIK3iICqhMlREu8zu%2Be5WpaCUA3K9Qu7mI5kLTcZXZlOGZBu9A578rzZRBxfxNYuBZAPd7XlEvkUsp9uhurdxYALfj9caqOHbwFTC6hhkXYASTSPpaZ3qACc8OXTaYzXgOyekwPKMNkJIAIkMlhtVFdkaQes48738%2BHmZd9qhjZDEs%2BsyWY2TlsBCP%2FskMWAm0q9xQrMG2DbmxtwgRiDhx8zoKcvDkpyRs9Ujbj8n9jKb1jFMe1vjKLeoce44LhRKGyqVz37s75rtYS%2Fw1dUZMBeXSGz7jXRowp4mn%2F61oHx9UZROq2FgTmQrIctPo4aZd%2BU9zialZTNsHGAjrFQ6B6YoUMfkQZWuIlu8%2FoaAzDimipUyIRIejHL%2BBNk5TrjX66FpSagJMjbAxG63tawb3rbGoB5gyIfIder7WZCBezwXZZU4TI%2BhDI04FCZUYcaEPUs6AVaVsMDCW%2FAJoU01nCoLPPwKmFPwrymamf4EjyxoaoZCSbYDpdxPIFh05%2BJBWYr9IS5rys7in7o%2Bi993fwYP%2BduesDRNJoPN1Dd9i79C%2Bmcvxbha7GuoUIKh%2Fc4c44kKRYvF1sn6sKeTP%2BNBNuTiqMyYfoa6MSOa9cTnmsw1D89ylBYeMf85TyZRIktdexmZzhIGeEvYjSoEV81OtJn2UgpLSMItJToRDvcWkDPfDN%2BKmmA8HLhFioLefgoSZmzEIkrB87dBQ3tAiNbr6n6mVdgFcJsod3nKkxlq3HOS6C4d5nAMxAhFcjJVbHu0aWXvUVfgvnOM3Iygq3egDPHq0FfvVaUpzxs1%2B76elyaRBkmkD8XFjQo8RdMTfaxZrujfIRBiaqKMXK6yQNxnNo6qASV%2FWqeoQq0xeQfjzZVd7hiC9UWusR5MdStU%2FbGXNIxBqQosLkSquD1b6FBTQTkLtUyUuHCEg5QKmEHqQX3QTVib2hshUCqKkh2A7zQxz4gs5nJpE%2Fo5VdeeVX%2FXwQWn1bY%2Bndm0bmAnTUfs6Z0%2BAyN4%2Bit1sN8lfGb0BLJz2tzI9Tfwsi4ABrDOVrVKcjGJ4bZKt3BQoLCpifmH558ESzYmMOn0eZ8K9VFVjuEvrdYtOL9SJkw4iPt%2BFNQo47Yat%2Br1%2FLDZo3%2BGZc8iwkpNgm%2FJYa5Of%2BulG2n9PTXOn6IEu2ojX7WNGvcTl6paA%2FLlSspDQ7DmxMYyffOazJKmDkXPTQWLMtrPdVoU4OlIptXshGU5e117crLTJacyotZm9rK%2FLN0iuS9Cc4B6Gejh%2F5LgvkM0M0fWtrkon0IJU1bZTpQt%2BpKFhy3l8Gm%2BjuRA7Yz%2FZhSXoiLwQZ7ablXZTSEMWbwnP%2FugFxrSyP0k3Cn39HASpvdvYNGHstqKjOHOUQ4ATh0O1NhVO8ng9lSbgnllxNLcTJkO1965xNtMNDFxhRQPgb9AWADZTg7EzGlKdxbNXOvXPgjYGwd1%2B%2Fc9P75lujpzXHm%2FaeydFhxULBdaCjiOShcOrnsUvLzFyVJqOTRe9J9%2FgBXaeOWeS1U%2FDfq36QhBmdubDs5Y6xvjY6APitDI6Oq%2Bw1qm8pUBPFKsfPD640KEaYa2q8%2FRqswwwfESsFS9wjXouOaHFq56l1Whuqr1DJu1PzjMKTn7QSFNDPsPj66kUPeKrkj81knFM2d2VAK%2BRXuEzib3fi2akkV0E7%2B8ajOcb1OrFxf93UcBQ1Tz%2BBEjv2g78etR3CbZ%2BXxrUEQifvgeKax1WsfP%2BpumstvNUa43CjOpgoN4nH75EQz53rUY6IcVQPx0jOQFCh4Msat8Adk6UX7eat6TAMzqtiJ%2BFLpCvmtkkVrY1OoPd2F0a7E6vEL5Y7MzkABoptbFFYUY30TSrPp4mTJ9E2NJ8rCK7YnqXDSpZPYMSeb5cxaFO38yUH47G5Vf4BULjRP6HN%2BNVtzjeQxLM86xdVloIwys%2FJw4P64WkXYtf%2FSwCmQnF19a1fmfM9JTNY0bhq%2FYuAowehqWrDp9ttbc23jIoUfSoElQP2lbFln1XM2VYrRT1XNaGJ9a7RR7C86oMqFskpy1RLrmvfieL3XwGVYVaiOTsRsIcW5Wspp12%2F1OvO8lWw7JUApHBeclvbwrj3kchvsIgAO7xjBWkARneDpGUVFMmR6FQ5OdcqIVFeE8KJ29GEnEwVKrJ5Ul5wyRB%2FsbxhCMqDaruHbwD8Iq45tDR0OLlfrz5ynA3A6NB8m3ZjuBVKd0kH1Rkj6CneERlxB6Q1NES6h97INPVyDk5n1SvKf2tIpw5vDvXYGTqpWzXRb2GGyUAvqhb6aOGwhxCtgMj2jkhxYHBZNIu3IerZEscKGT97lJtMEA4NKk8eGz1xlWKCQzL9Ns9QybKf1t4eWv1I7u5BU4CgkBoq3A4LDq8v9rr4XtfDfTIaC5MSsUsab%2FK5eR8vo5vTkDAfxT%2B6H4um%2BJRI9dh6sSSliNM317ONSgd8Es3KyO%2BsCXWzjTgb4PLXktriAr8NEvvFEAecid6dx5OBzj%2BGY0WYvYtgimywXCIrTuyGNH9TM%2FfKt33BvA8SE%2BRGfGMsz4%2F2%2Be5llkYS24PSiyJ1CxmjbkyFUmYd6GZSdI1VkZd4GzIQKdFAjRhXu0W1w0dDhtuC7d%2BZ6AKm7aMC2LAUaj6H2jZMmWVJrwOyCbScmKEbk4W%2Fw9jsiajg3fGnx7kEHM4Wdl6UXCnN5WWaJo21FaI4et1bFeC%2Fq4fS17SFoTTcU5Z1cEVtjU1Rsb6BoMiJrJ5yz%2FShE2C6z%2FSFTZpV1qYFEfa%2BkVCvd6AJi4AtgpoX0q5pe9W8C4EH8c2P%2BTW2L5%2FnTg4pgexSEUBtb%2B7BVQa0pLMcht52IHnk3EYImnSTe%2FnDQBROrxiiLuUsZ2Bi%2BE46%2FtS5hMGGEs%2F8o1TGsmymVu8jL8EhUHzoRLgS6qqZCaFZ4CQEjq27Y4Y8Nkm7pov1sVgECLj%2BMk2FWpWXnZ4rFS48bS59QMIUttrfCwl2lyLW0JnPap6QNiabM%2FEmymy3fAxg3zKgRarAtVJ7sR%2FZupIwCvNx6qkbjduuV4%2BO5JARU8h5qTRBlCY9kd7ab4Bqr0tkLzw0XxOaBtqMO5Q3%2FXxzvp%2FlbGBfNv1lbmpPfazc8VkqgU1%2F6VWASTy%2FVjaa3AWKCgzPxE7W7hClqyfy3Bu91swU617zlJ5UvEB4K26y8Ijax%2BrQSYupZVOW7rbuYQmkCyKtRUSuuDdCik7pzaLs%2B4rkXt8NLoUDNI6TUiJtDALO6wTgfYDTwtO2Du5jUQoRE3CWZlyo9hHuFwppndNd55MrBduWwOQM5xwhD%2BpKx2W3ImTUwBoY4YwxcfqxRx2N6FMEw%2FI3%2BwJMrITMgEa%2BCEScooQ8KUc8vO%2Fqn8X7xlh0u7s0BNJ3CD7%2BRYev3yZBGluSKsoLQYKbBksILgCkBYhJLpw0mRXXZUsh9t3v%2FTjZP88h2Co6%2B4%2FVwu5sQxZtXTbzYcCmUCAq5KCqwaohq%2Fq35RYuKQ1yTQ4NTnyb7USDodgKGiaBxrACJLRMbxsg83vG4WIT4%2F11qFNhDs0J37yHXlTIFyCMOY%2FACMLQ4v2WO75%2F6Il%2BWZ6eA4Pucc6U34TAWyEjjCPNYiGpnFcRUb1SNnTUWQW9iGJPWo6W9zNsDJX14VXC8MEjTQlTI8OjhJ1QEqVRDx1M%2Fke%2FXyrlykEtoDxPKYcMybDicG%2F0GDm5P1tMQ7A73dlpmvZxHB7Onxj9vgu2DZVJvQo7qXG9f3FQCzJiUH5ltmot%2BeAevKa72pEqPKb2G4FMSjk%2FgOeFCJuus1QjG%2FvKXHqVDi4WMPUCoXdI2qhF9DhbV%2BzPJX0lUq0jrO2IIwnbo%2B5miYmOllA5GCpAmN7ReQqvBHZ2sUNliI314CtEkgkCecVFDkw0379a1E7NHBRXuh6cQrb8fp4hlBXqV0KPL1BE7Of%2BL%2Fvj7JqgoqLcnFqqLRcTTYHU4oL%2F4cEkxXICK3akQTVnS7xnfEJHCnr%2FfADZALQeHOJv9m3VUjUn5O9W3QW%2BsVPHqtqG40%2F%2B7YhrHAm8z9PTiFekOXRkM0h0dyVS3CtEWG%2BEFx0i7IHyoR3kPel5ULNhePAVx6uBgD07PhtoBxLKSZioP0xpzXdrXrV5YWzdANhi1YArOaujN%2FbSQPVYypKQAAAU5xv7le9kfGQMiThpAI5NHNvBHuzduxKUupF5JRhMW3xrPXYdZducHvsbmsu%2BdOgc27q2D%2BprWmwGfDvV3pzWcn%2B3VwAEMhXIIOqk42p6%2BllBpScXlEE0D516oFUAtxtSDwmOUpzIJkdAzmwi5558UBKeYjJRTfkYRhrrjc0rid9nM11TsuWXHzr5hDH6J9jRXtLgEQr8Y5Dr7PYlh7XXIQJPhFx3bEGq9SxlRHd2QoEKFUuhuY602YPtOKvlClzvHdPP0Rcgpbt5EODW3OQ3o3KB3ORGt7aGNotlBhyY%2BYCUJj7Pi8Kfqv5W0E3Mt6TUmuk%2Ba0Xi04xFshyXY5hdkwzKQXxm7lXmR4tyiPhW6G4NSHaaz4UObHUnmntAeX4iXrcnmjbPUmV6%2FodfwMdoTevMfYB7Yj%2BTn%2BDgAMCdpr45Fj%2FyqdcJfr9ZH9DWxm0vDsaCin4uiWGD%2B2wdTHePv1LD60Zboce%2F12UWw1Mhg2jyWC1NRCseHJwTe8BAfn%2F0QoUEZKt3nDupHpOc8DM%2Fqezr2ZVlvj74sDvP6wm3K1froWRHj4mJuG3cThCWFi1RtSQmBSqVFMbiKfF1e67JKegWmMjY4vmO1mcNRzCYYAvIkWmKNphHYfyNoXfjT%2BSLgGFTEqN2Z36V4Yc7tlKMJJdULbXDWzQ2%2F%2BThEnu4BF5vr51bdgej4aECtvZ33f3Jj6FbD%2Fm6YUaO602jXKpTKkv5QjQk%2FKTvbkgHph87J5aa455oI7WfVj8TesvLvQ8%2BnitrYwpbCeItvR%2BQm61N7nI3DAZDMoSx1DKP10VjQYqt9pFI0b4CATH7Z2lS%2FNDvvbKiaV1diqWwfExagYH054VBOJm5eZLi%2FsAGVGM4sShi04KLun4PHIzqKaLdSN5Du2%2FWpotDK5E2A4Gysz3fa9tAOIgb9LUyc6QdQbyzGDIeRL1PT8%2B0sMjfy2TN43DhPNWVPb7bQpbcJZxogpSkCUDs%2FP%2BdpIuo715tfhMwljyQYsxHI%2B9mCmaJHYwjhffWujIzQAnd2Pu1bO47iDWkpYjxQKa2EA%2F9wKTlO860E0n2ftRWmxvS395hcTY0nYKMtXEiMFc4q9psDfTEkOPL%2BeIwwlFhMeVr9lXwQ969r0%2F%2BNwh3uprHiSoSoZsLYThks970ahTl1p87YxTF6R%2BzMdBm2oxYfOxCWXabQ2fFgEAdFKd7F3FJL8dba4hkxTQUOb4JRWV5j9TB2yAJazEnFSgEsWquEhDauGnJJ7TUsRcx0Yq0D%2Bhxk%2Brj5HQCbA4kMA%2FzIDHJb9dNqV4Guivp%2BsvGVpkCOHzx8Wo4x47RN3XtqXEGeiAZKjI%2F9dO81UfuFWNkULYLZQ8Y%2FHaep47B0QLELoEUx6ZpMWnBqyvlThzQLoyKLcNSevGBsDZ%2BTFmM2BVmgcTjI7bW3RcG6v30nKhUf5ipUO5VNVuHFuVJ9uFu5vzKyUVBlkOYj1UHmbl%2F%2Bng1ug3bBRmzzqc452ycDY2v9YjNjxqw6YmB7a98zmE0YaZf6QXtXLnCic%2BK5reKQ1WM8j1AICRAsUeRsZe%2BzFhgeBrvrHC6KiPU045Q72S7ZTbvlqJ46doL7Zht6zhWuV9yS3fhxUGRHnXvDfThmRfTRQt8zLO9PFTWZPZbwi6a4s%2FZQTFOXPLsj%2BB1pvSZ0xBBdI1KN4WHp2srisC2kKM3MrRgefrA7aIcrj37sfimlctLTpQ1JTCsxZC9g1yXpY7mCweYQ3Qx8Qhub44ncAWzTC5z1ciwsCytDnvpZM4l4vdbKlPksUho50tC%2BPZl4CtenZ09%2FMPY%2BNqwq1RmdvLPbgjmXRzn8hr8y%2FoN0n9PyThMDWep4NO%2B9IoCSRUZFnqS4bSZZ%2BX%2BrC%2FjdH3ry8TjYvQZ8BtVMYkbg4bovwwxDRX8%2FU73Se6zrEOhwKgvVxdBWf1KJO66UqRaT2nYqI8%2FbxXF7OTmXINjMpVtVAdpzWgo0zb4hZEF0oyTbTZo3MbJo13N91t4IPNUScCUzc8pmVCL9aH8li66cATplGiBgNOp2r%2BHQtuQeKhCORSlDk7NX74r3pa%2Fip9NB0TDd0zBG1AIf5q5evtvQCbjdnyhyiDSMiXi5CnHBMSkDXIiVLJFOvBS6iwkQWQZtG3tV4vvKpinoBvqa1SjlQDh3SNnzuZvFtFME%2BwOt4aZvEgmkBbvX8McUKNEdn4otUewWfSsAgF6EHfnSnRB75B7OVZqAxsh15lifIksaWsjIrhhVuYWQLq6u%2Fjm%2BYbzRmzqQrsF6sBmYz2JNDq8sg54vH%2Bv%2FolIFrvntreGZZdbva87C7OB6iVzX6Yq9xhHno4GFYHD7qFA4UGCKgcEYg%2F6EgStrmturQI0D099NdufP1P%2Fjch6w)

Each randomised story about serious issues includes an advertisement regarding something in the story. The stories also get interrupted by intrusive ads that interfere with your reading. Through parody, my goal was to make a mockery of how much it has infiltrated the journalism industry and prompt critical thinking about how interference in advertising affects our access to information. The news should aid in empowering democracy, so why does it seem like its primary concern is to attract consumers and generate ad revenue? Try refreshing the Tracery page to look at all the different combinations of stories you can get!

If my resources allowed me, I would have had the ads pop up without warning while you were scrolling to better model what happens on news sites and showcase the manipulation and interference methods that corporations use so these advertisements invade your screen and command your attention. This project gave me good practice in computational thinking, particularly by thinking at multiple levels of abstraction as I conceptualized all of the outcomes possible through Tracery. Overall, this process made me rethink the journalism industry through the critical lens of a communications student.

This has been my most unique project so far, and I loved dabbling in the world of journalism for this one. Tracery is a uniquely fun tool, and the possibilities for creation are endless!
